package store

// postgresBaseline is the Advanced-mode schema: the SQLite schema after all
// SQLite migrations 1..8, collapsed into one DDL blob. It is recorded as
// schema_migrations versions 1..8 so version numbering stays aligned with
// SQLite from version 9 on (see migrations.go).
//
// Translation rules from the SQLite schema (see plan §3):
//   - INTEGER PRIMARY KEY            -> BIGINT GENERATED BY DEFAULT AS IDENTITY
//     (BY DEFAULT, not ALWAYS: the migrator inserts explicit ids then setval()s
//     each sequence past max(id)).
//   - INTEGER flag/counter columns   -> BIGINT (Go scans int64; 0/1 booleans stay integers).
//   - TEXT stays TEXT, timestamps included (store.TimeLayout sorts lexically).
//   - Partial indexes, ON CONFLICT, composite PKs copy as-is (already portable).
//   - No WAL/pragma clauses (SQLite-only).
const postgresBaseline = `
CREATE TABLE projects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_kind   TEXT NOT NULL,
    identity        TEXT NOT NULL UNIQUE,
    display_name    TEXT NOT NULL,
    first_seen_at   TEXT NOT NULL,
    last_seen_at    TEXT NOT NULL,
    memory_disabled BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE sessions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id         TEXT NOT NULL UNIQUE,
    project_id          BIGINT NOT NULL REFERENCES projects(id),
    assistant           TEXT NOT NULL DEFAULT 'claude-code',
    started_at          TEXT NOT NULL,
    ended_at            TEXT,
    end_reason          TEXT,
    model               TEXT,
    input_tokens        BIGINT NOT NULL DEFAULT 0,
    output_tokens       BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens   BIGINT NOT NULL DEFAULT 0,
    cache_write_tokens  BIGINT NOT NULL DEFAULT 0,
    transcript_path     TEXT,
    sync_uid            TEXT,
    synced_at           TEXT,
    sync_dirty          BIGINT NOT NULL DEFAULT 0,
    memory_distilled_at TEXT,
    summary             TEXT
);
CREATE INDEX idx_sessions_project_started ON sessions(project_id, started_at);
CREATE INDEX idx_sessions_open ON sessions(ended_at) WHERE ended_at IS NULL;
CREATE UNIQUE INDEX idx_sessions_sync_uid ON sessions(sync_uid) WHERE sync_uid IS NOT NULL;
CREATE INDEX idx_sessions_unsynced ON sessions(project_id) WHERE synced_at IS NULL OR sync_dirty = 1;

CREATE TABLE events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT NOT NULL REFERENCES sessions(id),
    kind        TEXT NOT NULL,
    detail      TEXT,
    occurred_at TEXT NOT NULL,
    sync_uid    TEXT,
    synced_at   TEXT
);
CREATE INDEX idx_events_session_time ON events(session_id, occurred_at);
CREATE UNIQUE INDEX idx_events_sync_uid ON events(sync_uid) WHERE sync_uid IS NOT NULL;
CREATE INDEX idx_events_unsynced ON events(session_id) WHERE synced_at IS NULL;

CREATE TABLE diagnostics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TEXT NOT NULL,
    component   TEXT NOT NULL,
    message     TEXT NOT NULL
);

CREATE TABLE memories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT NOT NULL REFERENCES projects(id),
    session_id    BIGINT REFERENCES sessions(id),
    content       TEXT NOT NULL,
    kind          TEXT NOT NULL,
    origin        TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'active',
    superseded_by BIGINT REFERENCES memories(id),
    branch        TEXT,
    commit_hash   TEXT,
    captured_at   TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    edited        BIGINT NOT NULL DEFAULT 0,
    personal_only BIGINT NOT NULL DEFAULT 0,
    team_uid      TEXT,
    shared_at     TEXT,
    share_error   TEXT
);
CREATE INDEX idx_memories_project_active ON memories(project_id, captured_at DESC) WHERE status = 'active';
CREATE INDEX idx_memories_session ON memories(session_id) WHERE session_id IS NOT NULL;
CREATE INDEX idx_memories_share_pending ON memories(project_id) WHERE team_uid IS NOT NULL AND shared_at IS NULL;

CREATE TABLE team_memories (
    uid            TEXT PRIMARY KEY,
    project_id     BIGINT NOT NULL REFERENCES projects(id),
    author         TEXT NOT NULL,
    author_former  BIGINT NOT NULL DEFAULT 0,
    content        TEXT NOT NULL,
    kind           TEXT NOT NULL,
    origin         TEXT NOT NULL,
    status         TEXT NOT NULL,
    contradicts    TEXT,
    flagged        BIGINT NOT NULL DEFAULT 0,
    mine           BIGINT NOT NULL DEFAULT 0,
    branch         TEXT,
    commit_hash    TEXT,
    captured_at    TEXT NOT NULL,
    updated_at     TEXT NOT NULL
);
CREATE INDEX idx_team_memories_project_active ON team_memories(project_id, captured_at DESC) WHERE status = 'active';

CREATE TABLE team_sync_state (
    project_id  BIGINT PRIMARY KEY REFERENCES projects(id),
    pull_cursor TEXT NOT NULL DEFAULT '',
    endpoint    TEXT NOT NULL DEFAULT ''
);

CREATE TABLE memory_team_supersedes (
    memory_id BIGINT NOT NULL REFERENCES memories(id),
    team_uid  TEXT NOT NULL,
    PRIMARY KEY (memory_id, team_uid)
);
`

// migrationsPostgres holds Postgres migrations from schema version 9 onward, in
// lockstep with the SQLite `migrations` slice (append to both together). The
// migrations_lockstep_test guard asserts the two slices describe the same
// schema version.
var migrationsPostgres = []string{
	`
ALTER TABLE sessions ADD COLUMN parent_session_id BIGINT REFERENCES sessions(id);
ALTER TABLE sessions ADD COLUMN agent_type TEXT;
ALTER TABLE sessions ADD COLUMN agent_prompt TEXT;
CREATE INDEX idx_sessions_parent ON sessions(parent_session_id) WHERE parent_session_id IS NOT NULL;
`,
	`
ALTER TABLE sessions ADD COLUMN memory_checkpointed_at TEXT;
`,
	`
CREATE TABLE memory_usage_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions(id),
    project_id BIGINT NOT NULL REFERENCES projects(id),
    scope      TEXT NOT NULL,
    memory_id  BIGINT,
    team_uid   TEXT,
    retrieved  BIGINT NOT NULL DEFAULT 0,
    cited      BIGINT NOT NULL DEFAULT 0,
    first_at   TEXT NOT NULL,
    last_at    TEXT NOT NULL,
    synced_at  TEXT,
    sync_dirty BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX idx_memusage_session_ref
    ON memory_usage_events(session_id, scope, COALESCE(memory_id, 0), COALESCE(team_uid, ''));
CREATE INDEX idx_memusage_unsynced ON memory_usage_events(session_id)
    WHERE synced_at IS NULL OR sync_dirty = 1;
`,
	`
CREATE TABLE session_model_usage (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         BIGINT NOT NULL REFERENCES sessions(id),
    model              TEXT NOT NULL,
    input_tokens       BIGINT NOT NULL DEFAULT 0,
    output_tokens      BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens  BIGINT NOT NULL DEFAULT 0,
    cache_write_tokens BIGINT NOT NULL DEFAULT 0,
    synced_at          TEXT,
    sync_dirty         BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX idx_session_model_usage_ref ON session_model_usage(session_id, model);
CREATE INDEX idx_session_model_usage_unsynced ON session_model_usage(session_id)
    WHERE synced_at IS NULL OR sync_dirty = 1;
`,
	`
ALTER TABLE sessions ADD COLUMN memory_prompt_injected_at TEXT;
`,
}

// identityTables lists the tables whose id is a generated identity column, in
// FK dependency order. The transfer resets each one's sequence past the copied
// max(id); the lockstep test cross-checks the count against the baseline.
var identityTables = []string{"projects", "sessions", "events", "diagnostics", "memories", "memory_usage_events", "session_model_usage"}
